DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS book_management;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE book (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    writer TEXT NOT NULL,
    type TEXT NOT NULL
);

CREATE TABLE book_management(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bookid INTEGER,
    status BOOLEAN
);
