CREATE TABLE user(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL);

CREATE TABLE book(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT UNIQUE NOT NULL,
writer TEXT NOT NULL,
type TEXT NOT NULL);

CREATE TABLE book_management(
id INTEBER PRIMARY KEY AUTOINCTEMENT,
bookId INTEGER,
status BOOLEAN
);